eureka:
  client: # !!! gateway in bir eureka client oldugunu soyluyorum
    serviceUrl: #!!! bu clientin server i hakkinda bilgi verecegim
      defaultZone: http://localhost:8097/eureka
  # !!! yukarda discovery server ( register olacagi) portunu soyluyoruz

  # !!! butun requestler once gateway e gelecek daha sonra ilgili service
  # kismina gidecegi icin, gateway'e butun servisleri tanitiyoruz:
spring:
  cloud:
    gateway:
      routes: # !!! yonlendirme kurallarini belirleyecegimi soyluyorum
        - id: carModule
          uri: lb://car-service # lb= load balancer --> yuk dagilimi ( yedek server'a yonlendirebilir )
          predicates:
            - Path=/car/** # !!! sadece /car/** yol önekine sahip istekler Car servisine yönlendirilecektir

        - id: logModule
          uri: lb://log-service # !!! Yönlendirme yapılacak servisin adresini belirtir
          # !!! lb ( load balancer ): --> iki adet log-service sunucusu oldugunu varsayalim ve bunlardan biri gerçek hizmet sunucusu, diğeri yedek hizmet sunucusu olarak yapılandırılmış. Eğer gerçek hizmet sunucusunda bir arıza meydana gelirse, yük dengeleyici otomatik olarak yedek hizmet sunucusuna yönlendirme yapacaktır.
          #Bu sayede, servis kesintileri en aza indirilir ve kullanıcıların hizmete kesintisiz bir şekilde erişmeleri sağlanır. Yedek hizmet sunucusu, gerçek hizmet sunucusunun yerini alarak, kullanıcıların hizmete erişimlerini devam ettirmelerine olanak tanır.
          predicates:
            - Path=/log/**
